category/urls.py
from django.conf.urls import url
from . import views

app_name = 'category'

urlpatterns = [
    url(r'^create/$', views.create, name='create'),
    url(r'^update(?P<pk>\d+)/$', views.update, name='update'),
    url(r'^delete/(?P<pk>\d+)$', views.delete, name='delete'),
    url(r'^list/$', views.list, name='list'),
    url(r'^trash/$', views.trash_list, name='trash_list'),

]

sales/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^category/', include('category.urls')),

]

category/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    cname = models.CharField(max_length=20)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        db_table = "category"
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return str(self.cname)

product/models.py
from django.db import models
from category.models import Category


# Create your models here.
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    pname = models.CharField(max_length=120)
    quantity = models.CharField(max_length=120)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    total = models.CharField(max_length=120)
    description = models.TextField(max_length=150, null=True, blank=True)
    is_deleted = models.BooleanField(default=True)
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    class Meta:
        db_table = 'product'
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.pname

category/forms.py
from django import forms
from .models import Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'cname'
        ]

        widgets = {
            'cname': forms.TextInput(attrs={'class': 'form-group', 'placeholder': 'Category Name'}),
        }

category/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import CategoryForm
from .models import Category


def create(request):
    form = CategoryForm(request.POST or None)
    context = {}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('category:list')
    context['form'] = form
    return render(request, 'category/create.html', context)


def update(request, pk):
    context = {}
    try:
        datas = Category.objects.get(id=pk)
    except Category.DoesNotExist:
        messages.error(request, 'Nothing to update')
        return redirect('category:list')

    form = CategoryForm(instance=datas)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=datas)
        if form.is_valid():
            form.save()
            return redirect('category:list')

    context['form'] = form
    return render(request, 'category/create.html', context)


def delete(request, pk):
    context = {}
    choice = request.GET.get('choice')
    context['status'] = choice

    if request.method == 'POST':
        try:
            datas = Category.objects.get(id=pk)
        except Category.DoesNotExist:
            messages.error(request, 'Category not found')
            return redirect('category:list')

        if choice == 'Undo':
            datas.is_deleted = False
            datas.save()
            messages.success(request, 'Undo Successfully')

        elif choice == 'Trash':
            datas.is_deleted = True
            datas.save()
            messages.success(request, 'Trashed successfully')

        elif choice == 'Delete' and datas.is_deleted is True:
            datas.delete()
            messages.success(request, 'Deleted successfully.')

        return redirect('category:list')

    context['url'] = reverse('category:list')
    return render(request, 'snippest/delete.html', context)


def list(request):
    context = {}
    datas = Category.objects.filter(is_deleted=False)
    context['datas'] = datas
    return render(request, 'category/list.html', context)


def trash_list(request):
    context = {}
    datas = Category.objects.filter(is_deleted=True)

    context['datas'] = datas
    return render(request, 'category/list.html', context)

product/views.py
from django.shortcuts import render, redirect
from .models import Product
from .form import ProductForm


# Create your views here.
def create(request):
    context = {}
    form = ProductForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('#')

category/templates/category/create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}

    <div class="container mt-2">
        <div class="jumbotron">
            <div id="form_layout">
                <div class="row mt-5">
                    <div class="col-md-8 offset-md-2">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label font-weight-bold">Category Name</label>
                                {% if form.cname.errors %}
                                    <div class="col-sm-8">
                                        {{ form.cname | add_class:"is-invalid" }}
                                        <div class="invalid-feedback">
                                            {{ form.cname.errors }}
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="col-sm-8">
                                        {{ form.cname }}
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                {% endif %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

category/templates/category/list.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}

    <div class="container">
        <div class="row mt-2">
            <a href="{% url 'category:create' %}" class=" btn btn-primary"><i class="fa fa-plus"> </i> Add</a>
        </div>
        <br>
        <div class="row">
            <div class="table-responsive">
                <table class="table table-hover table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>S.N</th>
                        <th>Category Name</th>
                        <th></th>
                    </tr>
                    </thead>
                    {% for data in datas %}
                        <tr>
                            <td> {{ forloop.counter }} </td>
                            <td> {{ data.cname }} </td>
                            <td>
                                {% if not data.is_deleted %}
                                    <a href="{% url 'category:update' data.id %}" class=" btn">
                                        <i class="fa fa-2x fa-pencil-square-o"></i>
                                    </a>
                                    <a href="{% url 'category:delete' data.id %}?choice=Trash" class=" btn">
                                        <i class="fa fa-2x fa-trash-o text-danger"></i>
                                    </a>
                                {% else %}
                                    <a href="{% url 'category:delete' data.id %}?choice=Undo" class=" btn">
                                        <i class="fa fa-2x fa-undo"></i>
                                    </a>
                                    <a href="{% url 'category:delete' data.id %}?choice=Delete" class=" btn">
                                        <i class="fa fa-2x fa-trash text-danger"></i>
                                    </a>
                                {% endif %}
                            </td>

                        </tr>
                    {% empty %}
                        <tr>
                            <td class="table-danger text-center" colspan="6">No Data</td>
                        </tr>
                    {% endfor %}

                </table>

                {#                <div class="text-center">#}
                {#                    <nav aria-label="Page navigation example">#}
                {#                        <ul class="pagination justify-content-center">#}
                {#                            {% if data.has_previous %}#}
                {#                                <li class="page-item">#}
                {#                                    <a class="page-link" href="?page={{ data.previous_page_number }}" tabindex="-1">&laquo;#}
                {#                                        Previous</a>#}
                {#                                </li>#}
                {#                            {% else %}#}
                {#                                <li class="page-item disabled"><a class="page-link" href="#">&laquo; Previous</a></li>#}
                {#                            {% endif %}#}
                {##}
                {#                            {% for i in data.paginator.page_range %}#}
                {#                                {% if data.number == i %}#}
                {#                                    <li class="page-item disabled">#}
                {#                                        <a class="page-link " href="#">{{ i }}</a>#}
                {#                                    </li>#}
                {#                                {% else %}#}
                {#                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>#}
                {#                                {% endif %}#}
                {#                            {% endfor %}#}
                {##}
                {##}
                {#                            {% if data.has_next %}#}
                {#                                <li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}">Next#}
                {#                                    &raquo;</a></li>#}
                {#                            {% else %}#}
                {#                                <li class="page-item disabled"><a class="page-link">Next &raquo;</a></li>#}
                {#                            {% endif %}#}
                {##}
                {#                        </ul>#}
                {#                    </nav>#}
                {#                </div>#}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load fontawesome %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/components-font-awesome/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extra_stylesheets %}

    {% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-sm bg-danger navbar-fixed-top">
    <a class="navbar-brand ml-1" href="{% url 'category:create' %}">
        <i class="fa fa-2x fa-home"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse ml-5" id="navbarNavDropdown">
        <ul class="navbar-nav">

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-tags"></i> Category
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'category:create' %}">Add</a>
                    <a class="dropdown-item" href="{% url 'category:list' %}">List</a>
                    <a class="dropdown-item" href="{% url 'category:trash_list' %}">Trash</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-money"></i> Purchase</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-btc" aria-hidden="true"></i> Sales</a>
            </li>
        </ul>
    </div>
</nav>

{% block breadcrumb_head %}

{% endblock %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">X</a>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

{% block content %}

{% endblock %}


<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>

{% block extra_scripts %}

{% endblock %}

{#<script>#}
{#$(document).ready(function(){#}
{#  $("#myBtn").click(function(){#}
{#    $("#myModal").modal();#}
{#  });#}
{#});#}
{#</script>#}

</body>
</html>

templates/snippest/delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="jumbotron">
                    <form method="post">
                        {% csrf_token %}
                        <h1 class="display-8">Are you sure, you want to {{ status }} this data?</h1>
                        <hr class="my-4">
                        <p class="lead">
                        <div class="col-lg-12 text-center">
                            <input type="submit" value="{{ status }}" class="btn btn-success">
                            <a href="{% url 'category:list' %}" class="btn btn-primary">Cancel</a>
                        </div>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}